### PR TITLE
Add punishment cog for if someone pings all the Mods at the same time

### PR DESCRIPTION
**Pull request by Hausemaster-sal**
Now there is the cog pingpunisher.py, if someone's message contains
a ping of the mods, in multiple channels they get pinged back. These
pings delete after 30S, can also be toggled on/off

### CODE REVIEW

**Comment by vcokltfre** [comment]
The @moderator and @admin pings are available so that in case of an emergency people can ping them, in such a case pinging them back would be really annoying, I'll discuss it with other people but I think it happens rarely enough that it doesn't warrant its own module, especially as those role pings can be turned off by WarLord or Sal anyway if it becomes annoying. Thanks for your willingness to help and contribute though, if you have more ideas feel free to try and implement them :D

**Comment by Hausemaster-sal** [comment]
Fixed that insane usage of + and strings instead of message.author.mention. Now there are duplicate commits for some reason though

**Comment by Hausemaster-sal** [comment]
Just use a patch file instead ffs https://drive.google.com/file/d/1y8vr1DAOS7xfyrVXM31X4MsEAuXgl9hF/view?usp=sharing

**Comment by vcokltfre** [comment]
I'll reiterate, The @ moderator and @ admin pings are available so that in case of an emergency people can ping them, in such a case pinging them back would be really annoying, we don't want salbot to autoping people.

**Pull request closed without merging**
